### ISSUE TITLE
INLA package not on CRAN anymore

### ISSUE THREAD

**Issue by MarkusKonk** [JonasWallin/BiasCorrection#1]
Hi @JonasWallin,

I tried to recompute the analysis which worked fine except for one issue. The INLA package is not on CRAN anymore. I recommend including 
`install.packages("INLA", repos="https://inla.r-inla-download.org/R/stable")` followed by `library(INLA)`
However, I am not sure about the versions so it might be worth to check the results

Kind regards,

Markus Konkol
Institute for Geoinformatics, Münster
[o2r.info](o2r.info) (Opening reproducible research)

**Comment by JonasWallin** [comment]
Thanks for noticing,

I added install instruction in the readme for installing the INLA package.

mvh
Jonas Wallin
